on:
  push:
    branches:
      - main

jobs:
  build_pihole_config:
    name: Build Pihole_config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pihole_config
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          show-progress: false

      - name: Docker registry login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{vars.REGISTRY_URL}} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker buildx ls

      - name: Build
        run: docker build --pull -t ${{vars.REGISTRY_URL}}:${{vars.REGISTRY_PORT}}/${{vars.IMAGE_NAME}}:latest .

      - name: Push to registry
        run: docker push ${{vars.REGISTRY_URL}}:${{vars.REGISTRY_PORT}}/${{vars.IMAGE_NAME}}:latest
  Send-Ntfy-Main-Notification:
    runs-on: ubuntu-latest
    needs: build_pihole_config
    steps:
      - name: Send ntfy merge message
        run: |
          curl ${{vars.NTFY_SERVER}} -Ld '{
              "topic": "docker_repo_push",
              "title": "Push to main",
              "message": "{\"repo\":\"pihole_config\", \"modified\":[\"${{ join(github.event.head_commit.modified,'\", \"' )}}\"], \"author\":\"${{github.event.head_commit.author.email}}\"}"
            }'
